In [2]:
api_key = 'RGAPI-35c1b7c3-e9a6-4c8d-aa75-d4f1d44102bf'

In [57]:
# use riotwatcher (https://github.com/pseudonym117/Riot-Watcher)

from riotwatcher import RiotWatcher
import numpy as np

watcher = RiotWatcher(api_key)

my_region = 'na1'

In [271]:
# https://www.leagueofgraphs.com/rankings/summoners/na
# Doublelift, TF blade, thtr, Pobelter, CG Solo, Tony Top,

summoner_id = watcher.summoner.by_name(my_region, 'Jurassiq')

KeyboardInterrupt: 

In [267]:
print(summoner_id)

{'id': 19587365, 'accountId': 32281250, 'name': 'Tony Top', 'profileIconId': 3551, 'revisionDate': 1532984182000, 'summonerLevel': 127}


In [268]:
summoner_id['accountId']

32281250

In [269]:
matches = watcher.match.matchlist_by_account(my_region, account_id = summoner_id['accountId'])

In [270]:
# pull all matches from api

for i, cur_match in enumerate(matches['matches']):
    cur_match_id = cur_match['gameId']
    match = watcher.match.by_id(my_region, match_id = cur_match_id)
    fout = './dat/match_' + str(cur_match_id) + '.json'
    print(i, cur_match_id, fout)
    with open(fout, 'w') as fp:
        json.dump(match, fp)

0 2836050929 ./dat/match_2836050929.json
1 2836015259 ./dat/match_2836015259.json
2 2835988988 ./dat/match_2835988988.json
3 2835984590 ./dat/match_2835984590.json
4 2835990464 ./dat/match_2835990464.json
5 2835966589 ./dat/match_2835966589.json
6 2835954180 ./dat/match_2835954180.json
7 2835951719 ./dat/match_2835951719.json
8 2835874509 ./dat/match_2835874509.json
9 2834840602 ./dat/match_2834840602.json
10 2834786374 ./dat/match_2834786374.json
11 2834791460 ./dat/match_2834791460.json
12 2834766666 ./dat/match_2834766666.json
13 2834751618 ./dat/match_2834751618.json
14 2834733504 ./dat/match_2834733504.json
15 2834707521 ./dat/match_2834707521.json
16 2834658772 ./dat/match_2834658772.json
17 2834651947 ./dat/match_2834651947.json
18 2834646686 ./dat/match_2834646686.json
19 2834464586 ./dat/match_2834464586.json
20 2834437645 ./dat/match_2834437645.json
21 2834399361 ./dat/match_2834399361.json
22 2834400019 ./dat/match_2834400019.json
23 2834353492 ./dat/match_2834353492.json
24

KeyboardInterrupt: 

In [ ]:
matches['matches'][0]['gameId']

In [25]:
print(matches['matches'][0]['gameId'])

2834728655


In [64]:
cur_match_id = matches['matches'][1]['gameId']

In [28]:
timeline = watcher.match.timeline_by_match(my_region, match_id = cur_match_id)

In [31]:
timeline.keys()

dict_keys(['frames', 'frameInterval'])

In [36]:
timeline['frames'][0].keys()

dict_keys(['participantFrames', 'events', 'timestamp'])

In [44]:
len(timeline['frames'][0]['participantFrames'])

10

In [274]:
len(timeline['frames'][-3]['events'])

23

In [298]:
timeline['frames']

31

In [299]:
timeline['frames'][-1]['participantFrames']

{'1': {'participantId': 1,
  'currentGold': 486,
  'totalGold': 13086,
  'level': 16,
  'xp': 15573,
  'minionsKilled': 204,
  'jungleMinionsKilled': 5},
 '2': {'participantId': 2,
  'currentGold': 61,
  'totalGold': 11711,
  'level': 14,
  'xp': 12610,
  'minionsKilled': 224,
  'jungleMinionsKilled': 15},
 '3': {'participantId': 3,
  'currentGold': 1088,
  'totalGold': 10738,
  'level': 15,
  'xp': 13472,
  'minionsKilled': 46,
  'jungleMinionsKilled': 106},
 '4': {'participantId': 4,
  'currentGold': 670,
  'totalGold': 11403,
  'level': 15,
  'xp': 14336,
  'minionsKilled': 189,
  'jungleMinionsKilled': 5},
 '5': {'participantId': 5,
  'currentGold': 921,
  'totalGold': 7746,
  'level': 13,
  'xp': 10436,
  'minionsKilled': 42,
  'jungleMinionsKilled': 0},
 '6': {'participantId': 6,
  'currentGold': 1034,
  'totalGold': 8734,
  'level': 13,
  'xp': 11106,
  'minionsKilled': 8,
  'jungleMinionsKilled': 0},
 '7': {'participantId': 7,
  'currentGold': 671,
  'totalGold': 11471,
  'leve

In [65]:
match = watcher.match.by_id(my_region, match_id = cur_match_id)
fout = './dat/match_' + str(cur_match_id) + '.json'
with open(fout, 'w') as fp:
    json.dump(match, fp)

In [223]:
import json

# https://stackoverflow.com/questions/7100125/storing-python-dictionaries
fout = './dat/match_' + str(cur_match_id) + '.json'
with open(fout, 'w') as fp:
    json.dump(match, fp)

In [224]:
with open(fout, 'r') as fp:
    data = json.load(fp)

In [48]:
match.keys()

dict_keys(['gameId', 'platformId', 'gameCreation', 'gameDuration', 'queueId', 'mapId', 'seasonId', 'gameVersion', 'gameMode', 'gameType', 'teams', 'participants', 'participantIdentities'])

In [49]:
solo_vars = ['creepsPerMinDeltas', 'goldPerMinDeltas']
team_outcome = ['win']
time_deltas = ['0-10', '10-20', '20-30', '30-end']

dat_labels = []
print('labels:')
for v in solo_vars:
    for t in time_deltas:
        cur_label = v + '_' + t
        dat_labels.append(cur_label)
        print("('"+ cur_label + "', int),")

labels:
('creepsPerMinDeltas_0-10', int),
('creepsPerMinDeltas_10-20', int),
('creepsPerMinDeltas_20-30', int),
('creepsPerMinDeltas_30-end', int),
('goldPerMinDeltas_0-10', int),
('goldPerMinDeltas_10-20', int),
('goldPerMinDeltas_20-30', int),
('goldPerMinDeltas_30-end', int),


In [211]:
def get_winner(match):
    if match['teams'][0]['win'] == 'Win':
        return 0
    elif match['teams'][1]['win'] == 'Win':
        return 1
    else:
        return -1
    
def get_team_data(match_id, winner):
    team_dat = []
    
    team_vars = ['firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron', 'firstDragon', 'firstRiftHerald']
    
    for v in team_vars:
        cur_dat = match['teams'][winner][v]*1
        team_dat.append(cur_dat)
    return np.array(team_dat)

def get_role_lane(match_id, participant_id):
    role = match['participants'][participant_id]['timeline']['role']
    lane = match['participants'][participant_id]['timeline']['lane']
    return [role, lane]

def get_participant_data(match_id, winner, debug=False):

    participant_data = []

    m = len(match['participants'][0]['timeline'][solo_vars[0]])
    
    participant_ids = [(x+winner*5) % 10 for x in range(10)]
    
    for participant_id in participant_ids:
        [role, lane] = get_role_lane(match_id, participant_id)
        cur_participant_data = []
        for v in solo_vars:
            for i, t in enumerate(time_deltas):
                if i + 1 <= m:
                    cur_participant_data.append(np.round(match['participants'][participant_id]['timeline'][v][t],2))
                else:
                    cur_participant_data.append(-1)
                
        cur_participant_data = np.array(cur_participant_data,
                                dtype = object)
        participant_data.append([role, lane, cur_participant_data])
    
    return np.array(participant_data)

def process_match(match_id):
    winner = get_winner(match_id)
    team_dat = get_team_data(match_id, winner)
    duration = match_id['gameDuration'] / 60
    duration_id = int(duration/10) # 0 if last 10-20, 1 if 20-30, 2 if 30-40, 3 if 40+, etc.
    participant_data = get_participant_data(match_id, winner)
    return winner, team_dat, duration, duration_id, participant_data

In [212]:
match_data = process_match(match)

In [206]:
match_data[4]

array([['NONE', 'JUNGLE',
        array([7.9, 10.4, -1, -1, 360.5, 515.3, -1, -1], dtype=object)],
       ['SOLO', 'BOTTOM',
        array([7, 7.3, -1, -1, 262.9, 509.2, -1, -1], dtype=object)],
       ['SOLO', 'MIDDLE',
        array([8.7, 6.2, -1, -1, 402.1, 616.3, -1, -1], dtype=object)],
       ['NONE', 'JUNGLE',
        array([0.5, 1.8, -1, -1, 353.4, 411.4, -1, -1], dtype=object)],
       ['SOLO', 'TOP',
        array([1.6, 1.4, -1, -1, 207.9, 344.2, -1, -1], dtype=object)],
       ['DUO_CARRY', 'BOTTOM',
        array([9.3, 9.2, -1, -1, 301.3, 428.7, -1, -1], dtype=object)],
       ['DUO_SUPPORT', 'BOTTOM',
        array([1.1, 1.5, -1, -1, 174.6, 219.9, -1, -1], dtype=object)],
       ['SOLO', 'TOP',
        array([4.6, 8.1, -1, -1, 195.7, 333.4, -1, -1], dtype=object)],
       ['NONE', 'JUNGLE',
        array([0.8, 0.3, -1, -1, 186.4, 253.6, -1, -1], dtype=object)],
       ['SOLO', 'MIDDLE',
        array([6.5, 7.6, -1, -1, 239.4, 364.6, -1, -1], dtype=object)]],
      dtype=ob

In [86]:
match.keys()

dict_keys(['gameId', 'platformId', 'gameCreation', 'gameDuration', 'queueId', 'mapId', 'seasonId', 'gameVersion', 'gameMode', 'gameType', 'teams', 'participants', 'participantIdentities'])

In [91]:
match['gameType']

'MATCHED_GAME'

In [98]:
duration = match['gameDuration'] / 60
duration_id = int(duration/10)-1 # 0 if last 10-20, 1 if 20-30, 2 if 30-40, 3 if 40+, etc.
print(duration_id)

1


In [127]:
match['participants'][0]

{'participantId': 1,
 'teamId': 100,
 'championId': 202,
 'spell1Id': 4,
 'spell2Id': 7,
 'highestAchievedSeasonTier': 'MASTER',
 'stats': {'participantId': 1,
  'win': False,
  'item0': 1055,
  'item1': 3142,
  'item2': 3147,
  'item3': 3086,
  'item4': 3047,
  'item5': 0,
  'item6': 3363,
  'kills': 5,
  'deaths': 4,
  'assists': 4,
  'largestKillingSpree': 3,
  'largestMultiKill': 2,
  'killingSprees': 1,
  'longestTimeSpentLiving': 849,
  'doubleKills': 1,
  'tripleKills': 0,
  'quadraKills': 0,
  'pentaKills': 0,
  'unrealKills': 0,
  'totalDamageDealt': 120803,
  'magicDamageDealt': 1313,
  'physicalDamageDealt': 118121,
  'trueDamageDealt': 1368,
  'largestCriticalStrike': 1147,
  'totalDamageDealtToChampions': 22426,
  'magicDamageDealtToChampions': 1073,
  'physicalDamageDealtToChampions': 21050,
  'trueDamageDealtToChampions': 302,
  'totalHeal': 3889,
  'totalUnitsHealed': 3,
  'damageSelfMitigated': 7030,
  'damageDealtToObjectives': 5367,
  'damageDealtToTurrets': 90,
  'v

In [134]:
winner = 1
[print((x+winner*5) % 10) for x in range(10)]

5
6
7
8
9
0
1
2
3
4


[None, None, None, None, None, None, None, None, None, None]